<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="StockIssue.aspx.cs" Inherits="TransferStock" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <div>
        <fieldset>
            <legend><b>Stock Issue :</b></legend>
            <table>
            <tr>
                <td>Document Number *</td>
                <td class="auto-style1">:</td>
                <td><asp:TextBox CssClass="myInput" ID="txtDocumentNumber" runat="server" ReadOnly="true"></asp:TextBox></td>
            </tr>
            <tr>
                <td>Issue Store *</td>
                <td class="auto-style1">:</td>
                <td><asp:DropDownList ID="ddlIssueStore" runat="server" DataTextField="Name" DataValueField="Name" DataSourceID="SqlDS1" AutoPostBack="true" OnSelectedIndexChanged="DisplayItems"></asp:DropDownList></td>
            </tr>
            <tr>
                <td>Receipt Store *</td>
                <td class="auto-style1">:</td>
                <td><asp:DropDownList ID="ddlReceiptStore" runat="server" DataTextField="Name" DataValueField="Name" DataSourceID="SqlDS1"></asp:DropDownList></td>
            </tr>
            <tr>
                <td>Items</td>
                <td class="auto-style1">:</td>
                <td><asp:TextBox CssClass="myInput" ID="txtItem" runat="server" ></asp:TextBox></td>
                <td></td>
                <td>Quantity *</td>
                <td class="auto-style1">:</td>
                <td><asp:TextBox CssClass="myInput" ID="txtQuantity" runat="server" TextMode="Number"></asp:TextBox></td>
                <td><asp:Button CssClass="button1" ID="btnQuantityAdd" runat="server" Text="Add" OnClick="QuantityAdd" /></td>
            </tr>
            <tr>
                <td colspan="4">
                    <asp:GridView ID="gvItems" runat="server" DataKeyNames="Code" AutoGenerateSelectButton="true" AutoGenerateColumns="false" OnSelectedIndexChanged="AddItems" SelectedRowStyle-BackColor="#99ccff">
                        <Columns>
                            <asp:BoundField DataField="Code" HeaderText="Code" />
                            <asp:BoundField DataField="Name" HeaderText="Name" />
                            <asp:BoundField DataField="Batch" HeaderText="Batch Number" />
                            <asp:BoundField DataField="Expiry" HeaderText="Expiry Date" DataFormatString="{0:d}" />
                            <asp:BoundField DataField="Stock" HeaderText ="Stock On Hand" />
                        </Columns>
                    </asp:GridView>
                </td>
            </tr>
            <tr>
                <td colspan="8">
                    <asp:GridView ID="gvSelectedItems" runat="server" DataSourceID="SqlDS2" DataKeyNames="Code" AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" AutoGenerateColumns="false" Visible="false" HeaderStyle-BackColor="ControlLight">
                        <Columns>
                            <asp:BoundField DataField="Code" HeaderText="Code" />
                            <asp:BoundField DataField="Name" HeaderText="Name" />
                            <asp:BoundField DataField="Batch" HeaderText="Batch Number" />
                            <asp:BoundField DataField="Expiry" HeaderText="Expiry Date" DataFormatString="{0:d}" />
                            <asp:BoundField DataField="Stock" HeaderText="Stock On Hand" />
                            <asp:BoundField DataField="Quantity" HeaderText="Quantity" />
                        </Columns>
                    </asp:GridView>
                </td>
            </tr>
            <tr>
                <td colspan="8" style="text-align:right">
                    <asp:Button CssClass="button1 createbutton" ID="confirm" runat="server" Text="Confirm" OnClick="Confirm" />

                    <asp:Button CssClass="button1 backbutton" ID="cancel" runat="server" Text="Cancel" OnClick="Cancel" />
                </td>
            </tr>
        </table>
        </fieldset>
        <asp:SqlDataSource ID="SqlDS1" runat="server" ConnectionString="Data Source = localhost; Initial Catalog = HospitalIS; Integrated Security = true;" SelectCommand="SELECT * FROM Stores"></asp:SqlDataSource>
        <asp:SqlDataSource ID="SqlDS2" runat="server" ConnectionString="Data Source = localhost; Initial Catalog = HospitalIS; Integrated Security = true;" DeleteCommand="DELETE FROM AddItems WHERE Code = @Code" SelectCommand="SELECT * FROM AddItems" UpdateCommand="UPDATE AddItems SET Quantity = @Quantity WHERE Code = @Code"></asp:SqlDataSource>
    </div>
</asp:Content>

